.\" 
.\" Copyright (c) 2009 Gordon D. Carrie
.\" All rights reserved.
.\" 
.\" Licensed under the Open Software License version 3.0
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.6 $ $Date: 2009/07/23 22:50:38 $
.\"
.TH geog_lib 3 "geography functions"
.SH NAME
lonr, plat, gcdist \- geography functions
.SH SYNOPSIS
.nf
\fB#include "geog_lib.h"\fP
\fBdouble lonr(const double\fP \fIl\fP, \fBconst double\fP \fIr\fP\fB);\fP
\fBdouble plat(const double\fP \fIl\fP\fB);\fP
\fBdouble gcdist(const double\fP \fIlat1\fP, \fBconst double\fP \fIlon1\fP,
	\fBconst double\fP \fIlat2\fP, \fBconst double\fP \fIlon2\fP);
\fBdouble gcdistr(const double\fP \fIlat1\fP, \fBconst double\fP \fIlon1\fP,
	\fBconst double\fP \fIlat2\fP, \fBconst double\fP \fIlon2\fP);
.fi
.SH DESCRIPTION
Unless otherwise stated, longitudes and latitudes are expressed in degrees.

\fBlonr\fP computes a longitude equivalent to \fIl\fP in a longitude domain
centered about \fIr\fP.  The return value is \fIl\fP\ +\ i\ *\ 360.0 for some
integer i, and is in the interval [\fIr\fP\ -\ 180.0,\ \fIr\fP\ +\ 180.0).

\fBplat\fP computes the principle latitude corresponding to \fIl\fP.  Return value
is the latitude reached by going \fIl\fP degrees north of the Equator.

\fBgcdist\fP returns the great circle distance in degrees between points
(\fIlat1\fP,\ \fIlon1\fP) and (\fIlat2\fP,\ \fIlon2\fP).

\fBgcdistr\fP returns the great circle distance in radians between points
(\fIlat1\fP,\ \fIlon1\fP) and (\fIlat2\fP,\ \fIlon2\fP) where
\fIlat1\fP,\ \fIlon1\fP \fIlat2\fP,\ and \fIlon2\fP must be given in radians.
.SH SEE ALSO
\fBgeog\fP (1)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
