.\" 
.\" Copyright (c) 2009 Gordon D. Carrie
.\" All rights reserved.
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.15 $ $Date: 2009/12/08 20:21:12 $
.\"
.TH geog_lib 3 "geography functions"
.SH NAME
GeogLonR, GeogLatN, GCDist \- geography functions
.SH SYNOPSIS
.nf
\fB#include "geog_lib.h"\fP
\fBdouble GeogREarth(const double\fP *\fIr)\fP\fB;\fP
\fBdouble GeogLonR(const double\fP \fIl\fP, \fBconst double\fP \fIr\fP\fB);\fP
\fBdouble GeogLatN(const double\fP \fIl\fP\fB);\fP
\fBdouble GeogDist(const double\fP \fIlon1\fP, \fBconst double\fP \fIlat1\fP,
	\fBconst double\fP \fIlon2\fP, \fBconst double\fP \fIlat2\fP\fB);\fP
\fBdouble GeogAz(const double\fP \fIlon1\fP, \fBconst double\fP \fIlat1\fP,
	\fBconst double\fP \fIlon2\fP, \fBconst double\fP \fIlat2\fP\fB);\fP
\fBvoid GeogStep(const double\fP \fIlon0\fP, \fBconst double\fP \fIlat0\fP,
	\fBconst double\fP \fIdirn\fP, \fBconst double\fP \fIdist\fP, \fBdouble\fP *lon1\fP, \fBdouble\fP *\fIlat1\fP\fB);\fP
.fi
.SH DESCRIPTION
Unless otherwise stated, longitudes, latitudes, and other angles are expressed
in radians.

\fBGeogREarth\fP sets radius of the Earth to *\fIr\fP if \fIr\fP is not
\fBNULL\fP, and then returns the radius of the Earth.

\fBGeogLonR\fP returns a longitude equivalent to \fIl\fP in a longitude domain
centered about \fIr\fP.  The return value is \fIl\fP\ +\ i\ *\ 360.0 for some
integer i, and is in the interval [\fIr\fP\ -\ 180.0,\ \fIr\fP\ +\ 180.0).

\fBGeogLatN\fP returns the latitude reached by going \fIl\fP radians north of
the Equator.

\fBGeogDist\fP returns the great circle distance in radians between points
(\fIlon1\fP,\ \fIlat1\fP) and (\fIlon2\fP,\ \fIlat2\fP).

\fBGeogAz\fP returns the great circle azimuth (direction) in radians clockwise
from North from point (\fIlon1\fP,\ \fIlat1\fP) to point (\fIlon2\fP,\ \fIlat2\fP).

\fBGeogStep\fP computes the longitude and latitude of the point in direction
\fIdirn\fP and distance \fIdist\fP along a great circle from point
(\fIlon0\fP,\ \fIlat0\fP).  It places the longitude and latitude of the destination
point at addresses \fIlon1\fP and \fIlat1\fP respectively.
.SH SEE ALSO
\fBgeog\fP (1)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
