.\" 
.\" Copyright (c) 2009 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Licensed under the Open Software License version 3.0
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: $ $Date: $
.\"
.TH geog 3 "geography application"
.SH NAME
geog \- geography application
.SH SYNOPSIS
\fBgeog\fP \fIgeog_command\fP [\fIcommand_options ...\fP]
.SH DESCRIPTION
The \fBgeog\fP application calculates distances and angles on Earth's surface.
The \fIgeog_command\fP argument determines its behavior.  It must be one of
the following.
.TP
\fBgeog\fP \fBrlon\fP \fIl\fP \fIr\fP 
Computes a longitude equivalent to \fIl\fP in a longitude domain
centered about \fIr\fP.  The return value is \fIl\fP\ +\ i\ *\ 360.0 for some
integer i, and is in the interval [\fIr\fP\ -\ 180.0,\ \fIr\fP\ +\ 180.0).
.TP
\fBgeog\fP \fBplat\fP \fIl\fP
Computes the principle latitude corresponding to \fIl\fP.  Return value
is the latitude reached by going \fIl\fP degrees north of the Equator.
.SH SEE ALSO
\fBgeog_lib\fP (3)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
